/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["service-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["auth-register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["auth-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["catalog-list_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Equipment */
        get: operations["catalog-list_equipment"];
        put?: never;
        /** Create Equipment */
        post: operations["catalog-create_equipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{equipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Equipment */
        get: operations["catalog-get_equipment"];
        put?: never;
        post?: never;
        /** Delete Equipment */
        delete: operations["catalog-delete_equipment"];
        options?: never;
        head?: never;
        /** Update Equipment */
        patch: operations["catalog-update_equipment"];
        trace?: never;
    };
    "/api/my/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Equipment */
        get: operations["catalog-list_my_equipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{equipment_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Photos */
        post: operations["catalog-upload_photos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{equipment_id}/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Photo */
        delete: operations["catalog-delete_photo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{equipment_id}/busy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Equipment Busy
         * @description Занятые интервалы для календаря. Только время, без данных о клиентах.
         */
        get: operations["bookings-equipment_busy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quote Booking
         * @description Предпросмотр: сколько будет стоить и свободно ли время. Ничего не сохраняет.
         */
        post: operations["bookings-quote_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Booking */
        post: operations["bookings-create_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Bookings */
        get: operations["bookings-my_bookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Booking */
        post: operations["bookings-cancel_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner Bookings */
        get: operations["bookings-owner_bookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Booking */
        post: operations["bookings-confirm_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Booking */
        post: operations["bookings-reject_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Booking */
        post: operations["bookings-start_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Booking */
        post: operations["bookings-complete_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telegram/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telegram Status */
        get: operations["telegram-telegram_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telegram/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Link
         * @description Одноразовая ссылка на бота. По ней бот узнаёт, к какому аккаунту привязать чат.
         */
        post: operations["telegram-create_link"];
        /** Remove Link */
        delete: operations["telegram-remove_link"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_catalog-upload_photos */
        "Body_catalog-upload_photos": {
            /** Files */
            files: string[];
        };
        /** BookingCreate */
        BookingCreate: {
            /** Equipment Id */
            equipment_id: number;
            rate_type: components["schemas"]["RateType"];
            /**
             * Start
             * Format: date-time
             * @description Начало первой смены или часа, с часовым поясом
             */
            start: string;
            /**
             * Quantity
             * @description Часы или смены
             */
            quantity: number;
            /**
             * With Operator
             * @default false
             */
            with_operator: boolean;
            /**
             * Contact Phone
             * @description По нему позвонит владелец
             */
            contact_phone: string;
            /** Delivery Address */
            delivery_address?: string | null;
            /** Comment */
            comment?: string | null;
        };
        /** BookingEquipment */
        BookingEquipment: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Address */
            address: string | null;
            /** Cover Url */
            cover_url: string | null;
        };
        /** BookingParams */
        BookingParams: {
            /** Equipment Id */
            equipment_id: number;
            rate_type: components["schemas"]["RateType"];
            /**
             * Start
             * Format: date-time
             * @description Начало первой смены или часа, с часовым поясом
             */
            start: string;
            /**
             * Quantity
             * @description Часы или смены
             */
            quantity: number;
            /**
             * With Operator
             * @default false
             */
            with_operator: boolean;
        };
        /** BookingRead */
        BookingRead: {
            /** Id */
            id: number;
            status: components["schemas"]["BookingStatus"];
            rate_type: components["schemas"]["RateType"];
            /** Quantity */
            quantity: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** With Operator */
            with_operator: boolean;
            /** Delivery Address */
            delivery_address: string | null;
            /** Comment */
            comment: string | null;
            /** Contact Phone */
            contact_phone: string;
            /** Reject Reason */
            reject_reason: string | null;
            /** Rental Price */
            rental_price: number;
            /** Operator Price */
            operator_price: number;
            /** Total Price */
            total_price: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            equipment: components["schemas"]["BookingEquipment"];
            /** @description Для владельца: кто арендует */
            client?: components["schemas"]["Contact"] | null;
            /** @description Для клиента: контакт владельца после подтверждения */
            owner?: components["schemas"]["Contact"] | null;
        };
        /**
         * BookingStatus
         * @enum {string}
         */
        BookingStatus: "pending" | "confirmed" | "active" | "completed" | "cancelled" | "rejected" | "expired";
        /** BusyInterval */
        BusyInterval: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** CategoryRead */
        CategoryRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** Contact */
        Contact: {
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string | null;
        };
        /** EquipmentCreate */
        EquipmentCreate: {
            /** Name */
            name: string;
            /** Category Id */
            category_id: number;
            /** Description */
            description?: string | null;
            /**
             * Specs
             * @default []
             */
            specs: components["schemas"]["SpecItem"][];
            /** Address */
            address?: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Price Per Hour */
            price_per_hour: number | string;
            /** Price Per Shift */
            price_per_shift?: number | string | null;
            /**
             * Min Hours
             * @default 4
             */
            min_hours: number;
            /**
             * Operator Available
             * @default false
             */
            operator_available: boolean;
            /** Operator Price Per Hour */
            operator_price_per_hour?: number | string | null;
        };
        /** EquipmentListItem */
        EquipmentListItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            category: components["schemas"]["CategoryRead"];
            /** Address */
            address: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Price Per Hour */
            price_per_hour: number;
            /** Price Per Shift */
            price_per_shift: number | null;
            /** Min Hours */
            min_hours: number;
            /** Operator Available */
            operator_available: boolean;
            /** Operator Price Per Hour */
            operator_price_per_hour: number | null;
            status: components["schemas"]["EquipmentStatus"];
            /** Cover Url */
            cover_url?: string | null;
            /** Distance Km */
            distance_km?: number | null;
        };
        /** EquipmentPage */
        EquipmentPage: {
            /** Items */
            items: components["schemas"]["EquipmentListItem"][];
            /** Total */
            total: number;
        };
        /** EquipmentRead */
        EquipmentRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            category: components["schemas"]["CategoryRead"];
            /** Address */
            address: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Price Per Hour */
            price_per_hour: number;
            /** Price Per Shift */
            price_per_shift: number | null;
            /** Min Hours */
            min_hours: number;
            /** Operator Available */
            operator_available: boolean;
            /** Operator Price Per Hour */
            operator_price_per_hour: number | null;
            status: components["schemas"]["EquipmentStatus"];
            /** Cover Url */
            cover_url?: string | null;
            /** Distance Km */
            distance_km?: number | null;
            /** Description */
            description: string | null;
            /** Specs */
            specs: components["schemas"]["SpecItem"][];
            /** Photos */
            photos: components["schemas"]["PhotoRead"][];
            owner: components["schemas"]["OwnerPublic"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EquipmentStatus
         * @enum {string}
         */
        EquipmentStatus: "available" | "maintenance" | "inactive";
        /**
         * EquipmentUpdate
         * @description PATCH: передаются только изменённые поля.
         */
        EquipmentUpdate: {
            /** Name */
            name?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Description */
            description?: string | null;
            /** Specs */
            specs?: components["schemas"]["SpecItem"][] | null;
            /** Address */
            address?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Price Per Hour */
            price_per_hour?: number | string | null;
            /** Price Per Shift */
            price_per_shift?: number | string | null;
            /** Min Hours */
            min_hours?: number | null;
            /** Operator Available */
            operator_available?: boolean | null;
            /** Operator Price Per Hour */
            operator_price_per_hour?: number | string | null;
            status?: components["schemas"]["EquipmentStatus"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OwnerPublic */
        OwnerPublic: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
        };
        /** PhotoRead */
        PhotoRead: {
            /** Id */
            id: number;
            /** Url */
            url: string;
        };
        /** QuoteRead */
        QuoteRead: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Billable Hours */
            billable_hours: number;
            /** Rental Price */
            rental_price: number;
            /** Operator Price */
            operator_price: number;
            /** Total Price */
            total_price: number;
            /** Available */
            available: boolean;
        };
        /**
         * RateType
         * @enum {string}
         */
        RateType: "hourly" | "shift";
        /** RejectBody */
        RejectBody: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * SpecItem
         * @description Характеристика: «Глубина копания» → «5,9 м». Строки, потому что так их пишут люди.
         */
        SpecItem: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** TelegramLink */
        TelegramLink: {
            /** Url */
            url: string;
        };
        /** TelegramStatus */
        TelegramStatus: {
            /** Enabled */
            enabled: boolean;
            /** Connected */
            connected: boolean;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone?: string | null;
            /**
             * Role
             * @default client
             * @enum {string}
             */
            role: "client" | "owner";
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string | null;
            role: components["schemas"]["UserRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Telegram Connected */
            telegram_connected: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "client" | "owner" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "service-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    "auth-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-list_categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
        };
    };
    "catalog-list_equipment": {
        parameters: {
            query?: {
                /** @description slug категории */
                category?: string | null;
                /** @description Поиск по названию */
                q?: string | null;
                /** @description Максимальная цена за час */
                price_max?: number | string | null;
                /** @description Только с оператором */
                operator?: boolean | null;
                lat?: number | null;
                lon?: number | null;
                radius_km?: number | null;
                available_from?: string | null;
                available_to?: string | null;
                sort?: "new" | "price_asc" | "price_desc" | "distance";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-create_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-get_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-delete_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-update_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-list_my_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-upload_photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_catalog-upload_photos"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-delete_photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
                photo_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-equipment_busy": {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusyInterval"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-quote_booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-create_booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-my_bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-cancel_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-owner_bookings": {
        parameters: {
            query?: {
                status?: components["schemas"]["BookingStatus"][] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-confirm_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-reject_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-start_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-complete_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "telegram-telegram_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "telegram-create_link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "telegram-remove_link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
