/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["service-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["auth-register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["auth-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["catalog-list_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Equipment */
        get: operations["catalog-list_equipment"];
        put?: never;
        /** Create Equipment */
        post: operations["catalog-create_equipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{equipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Equipment */
        get: operations["catalog-get_equipment"];
        put?: never;
        post?: never;
        /** Delete Equipment */
        delete: operations["catalog-delete_equipment"];
        options?: never;
        head?: never;
        /** Update Equipment */
        patch: operations["catalog-update_equipment"];
        trace?: never;
    };
    "/api/my/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Equipment */
        get: operations["catalog-list_my_equipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{equipment_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Photos */
        post: operations["catalog-upload_photos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{equipment_id}/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Photo */
        delete: operations["catalog-delete_photo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{equipment_id}/busy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Equipment Busy
         * @description Занятые интервалы для календаря. Только время, без данных о клиентах.
         */
        get: operations["bookings-equipment_busy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quote Booking
         * @description Предпросмотр: сколько будет стоить и свободно ли время. Ничего не сохраняет.
         */
        post: operations["bookings-quote_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Booking */
        post: operations["bookings-create_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Bookings */
        get: operations["bookings-my_bookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Booking */
        post: operations["bookings-cancel_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner Bookings */
        get: operations["bookings-owner_bookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Booking */
        post: operations["bookings-confirm_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Booking */
        post: operations["bookings-reject_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Booking */
        post: operations["bookings-start_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Booking */
        post: operations["bookings-complete_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telegram/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telegram Status */
        get: operations["telegram-telegram_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telegram/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Link
         * @description Одноразовая ссылка на бота. По ней бот узнаёт, к какому аккаунту привязать чат.
         */
        post: operations["telegram-create_link"];
        /** Remove Link */
        delete: operations["telegram-remove_link"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geo Status */
        get: operations["geo-geo_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geo Search */
        get: operations["geo-geo_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geo Reverse */
        get: operations["geo-geo_reverse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Owner
         * @description Арендатор оценивает владельца
         */
        post: operations["reviews-review_owner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/renter-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Renter
         * @description Владелец оценивает арендатора
         */
        post: operations["reviews-review_renter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owners/{owner_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Owner Reviews
         * @description Публично: отзывы о владельце видят все, кто выбирает технику
         */
        get: operations["reviews-owner_reviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/{renter_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Renter Reviews
         * @description Только владельцам: отзывы об арендаторе помогают решить, подтверждать ли заявку
         */
        get: operations["reviews-renter_reviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Ratings */
        get: operations["reviews-my_ratings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["admin-list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["admin-delete_user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Equipment */
        get: operations["admin-list_equipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/equipment/{equipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Equipment
         * @description В отличие от владельца, администратор удаляет технику и с активными бронями
         */
        delete: operations["admin-delete_equipment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bookings */
        get: operations["admin-list_bookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/bookings/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Booking */
        delete: operations["admin-delete_booking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["admin-list_reviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Review */
        delete: operations["admin-delete_review"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Category */
        post: operations["admin-create_category"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Category */
        put: operations["admin-update_category"];
        post?: never;
        /** Delete Category */
        delete: operations["admin-delete_category"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminEquipmentRead */
        AdminEquipmentRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Status */
            status: string;
            /** Owner Id */
            owner_id: number;
            /** Owner Name */
            owner_name: string;
            /** Owner Email */
            owner_email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AdminReviewRead */
        AdminReviewRead: {
            /** Id */
            id: number;
            /**
             * Direction
             * @description about_owner — отзыв о владельце, about_renter — об арендаторе
             */
            direction: string;
            /** Rating */
            rating: number;
            /** Text */
            text: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Author Name
             * @description Имя и первая буква фамилии: «Анна К.»
             */
            author_name: string;
            /** Equipment Name */
            equipment_name: string;
            /** Subject Id */
            subject_id: number;
            /** Subject Name */
            subject_name: string;
            /** Author Id */
            author_id: number;
        };
        /** AdminUserRead */
        AdminUserRead: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string | null;
            role: components["schemas"]["UserRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Equipment Count
             * @default 0
             */
            equipment_count: number;
            /**
             * Bookings Count
             * @default 0
             */
            bookings_count: number;
        };
        /** Body_catalog-upload_photos */
        "Body_catalog-upload_photos": {
            /** Files */
            files: string[];
        };
        /** BookingCreate */
        BookingCreate: {
            /** Equipment Id */
            equipment_id: number;
            rate_type: components["schemas"]["RateType"];
            /**
             * Start
             * Format: date-time
             * @description Начало первой смены или часа, с часовым поясом
             */
            start: string;
            /**
             * Quantity
             * @description Часы или смены
             */
            quantity: number;
            /**
             * Contact Phone
             * @description По нему позвонит владелец
             */
            contact_phone: string;
            /** Delivery Address */
            delivery_address?: string | null;
            /**
             * Delivery Address Token
             * @description Подпись адреса из /api/geo/search
             */
            delivery_address_token?: string | null;
            /** Comment */
            comment?: string | null;
        };
        /** BookingEquipment */
        BookingEquipment: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Address */
            address: string | null;
            /** Cover Url */
            cover_url: string | null;
        };
        /** BookingParams */
        BookingParams: {
            /** Equipment Id */
            equipment_id: number;
            rate_type: components["schemas"]["RateType"];
            /**
             * Start
             * Format: date-time
             * @description Начало первой смены или часа, с часовым поясом
             */
            start: string;
            /**
             * Quantity
             * @description Часы или смены
             */
            quantity: number;
        };
        /** BookingRead */
        BookingRead: {
            /** Id */
            id: number;
            status: components["schemas"]["BookingStatus"];
            rate_type: components["schemas"]["RateType"];
            /** Quantity */
            quantity: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Delivery Address */
            delivery_address: string | null;
            /** Comment */
            comment: string | null;
            /** Contact Phone */
            contact_phone: string;
            /** Reject Reason */
            reject_reason: string | null;
            /** Total Price */
            total_price: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Reviewed
             * @description Клиент уже оставил отзыв о владельце
             * @default false
             */
            reviewed: boolean;
            /**
             * Renter Reviewed
             * @description Владелец уже оставил отзыв об арендаторе
             * @default false
             */
            renter_reviewed: boolean;
            equipment: components["schemas"]["BookingEquipment"];
            /** @description Для владельца: кто арендует */
            client?: components["schemas"]["Contact"] | null;
            /** @description Для клиента: контакт владельца после подтверждения */
            owner?: components["schemas"]["Contact"] | null;
        };
        /**
         * BookingStatus
         * @enum {string}
         */
        BookingStatus: "pending" | "confirmed" | "active" | "completed" | "cancelled" | "rejected" | "expired";
        /** BusyInterval */
        BusyInterval: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** CategoryRead */
        CategoryRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Spec Template
             * @description Характеристики для формы добавления техники
             */
            spec_template: components["schemas"]["SpecTemplateItem"][];
        };
        /** CategoryWrite */
        CategoryWrite: {
            /** Name */
            name: string;
            /**
             * Spec Template
             * @default []
             */
            spec_template: components["schemas"]["SpecTemplateItem"][];
        };
        /** Contact */
        Contact: {
            /** Id */
            id?: number | null;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string | null;
            /** Rating */
            rating?: number | null;
            /**
             * Reviews Count
             * @default 0
             */
            reviews_count: number;
        };
        /** EquipmentCreate */
        EquipmentCreate: {
            /** Name */
            name: string;
            /** Category Id */
            category_id: number;
            /** Description */
            description?: string | null;
            /**
             * Specs
             * @default []
             */
            specs: components["schemas"]["SpecItem"][];
            /** Address */
            address: string;
            /**
             * Address Token
             * @description Подпись адреса из /api/geo/search
             */
            address_token?: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Price Per Hour */
            price_per_hour: number | string;
            /** Price Per Shift */
            price_per_shift?: number | string | null;
            /**
             * Min Hours
             * @default 4
             */
            min_hours: number;
        };
        /** EquipmentListItem */
        EquipmentListItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            category: components["schemas"]["CategoryRead"];
            /** Address */
            address: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Price Per Hour */
            price_per_hour: number;
            /** Price Per Shift */
            price_per_shift: number | null;
            /** Min Hours */
            min_hours: number;
            status: components["schemas"]["EquipmentStatus"];
            /** Cover Url */
            cover_url?: string | null;
            /** Distance Km */
            distance_km?: number | null;
            /** Owner Rating */
            owner_rating?: number | null;
            /**
             * Owner Reviews Count
             * @default 0
             */
            owner_reviews_count: number;
        };
        /** EquipmentPage */
        EquipmentPage: {
            /** Items */
            items: components["schemas"]["EquipmentListItem"][];
            /** Total */
            total: number;
        };
        /** EquipmentRead */
        EquipmentRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            category: components["schemas"]["CategoryRead"];
            /** Address */
            address: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Price Per Hour */
            price_per_hour: number;
            /** Price Per Shift */
            price_per_shift: number | null;
            /** Min Hours */
            min_hours: number;
            status: components["schemas"]["EquipmentStatus"];
            /** Cover Url */
            cover_url?: string | null;
            /** Distance Km */
            distance_km?: number | null;
            /** Owner Rating */
            owner_rating?: number | null;
            /**
             * Owner Reviews Count
             * @default 0
             */
            owner_reviews_count: number;
            /** Description */
            description: string | null;
            /** Specs */
            specs: components["schemas"]["SpecItem"][];
            /** Photos */
            photos: components["schemas"]["PhotoRead"][];
            owner: components["schemas"]["OwnerPublic"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EquipmentStatus
         * @enum {string}
         */
        EquipmentStatus: "available" | "maintenance" | "inactive";
        /**
         * EquipmentUpdate
         * @description PATCH: передаются только изменённые поля.
         */
        EquipmentUpdate: {
            /** Name */
            name?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Description */
            description?: string | null;
            /** Specs */
            specs?: components["schemas"]["SpecItem"][] | null;
            /** Address */
            address?: string | null;
            /** Address Token */
            address_token?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Price Per Hour */
            price_per_hour?: number | string | null;
            /** Price Per Shift */
            price_per_shift?: number | string | null;
            /** Min Hours */
            min_hours?: number | null;
            status?: components["schemas"]["EquipmentStatus"] | null;
        };
        /** GeoStatus */
        GeoStatus: {
            /** Enabled */
            enabled: boolean;
        };
        /** GeoSuggestion */
        GeoSuggestion: {
            /** Address */
            address: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Token */
            token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MyRatings */
        MyRatings: {
            as_owner: components["schemas"]["UserReviewsSummary"];
            as_renter: components["schemas"]["UserReviewsSummary"];
        };
        /** OwnerPublic */
        OwnerPublic: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Rating */
            rating?: number | null;
            /**
             * Reviews Count
             * @default 0
             */
            reviews_count: number;
        };
        /** Page[AdminEquipmentRead] */
        Page_AdminEquipmentRead_: {
            /** Items */
            items: components["schemas"]["AdminEquipmentRead"][];
            /** Total */
            total: number;
        };
        /** Page[AdminReviewRead] */
        Page_AdminReviewRead_: {
            /** Items */
            items: components["schemas"]["AdminReviewRead"][];
            /** Total */
            total: number;
        };
        /** Page[AdminUserRead] */
        Page_AdminUserRead_: {
            /** Items */
            items: components["schemas"]["AdminUserRead"][];
            /** Total */
            total: number;
        };
        /** Page[BookingRead] */
        Page_BookingRead_: {
            /** Items */
            items: components["schemas"]["BookingRead"][];
            /** Total */
            total: number;
        };
        /** PhotoRead */
        PhotoRead: {
            /** Id */
            id: number;
            /** Url */
            url: string;
        };
        /** QuoteRead */
        QuoteRead: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Billable Hours */
            billable_hours: number;
            /** Total Price */
            total_price: number;
            /** Available */
            available: boolean;
        };
        /**
         * RateType
         * @enum {string}
         */
        RateType: "hourly" | "shift";
        /** RejectBody */
        RejectBody: {
            /** Reason */
            reason?: string | null;
        };
        /** ReviewCreate */
        ReviewCreate: {
            /** Rating */
            rating: number;
            /** Text */
            text?: string | null;
        };
        /**
         * ReviewDirection
         * @enum {string}
         */
        ReviewDirection: "about_owner" | "about_renter";
        /** ReviewRead */
        ReviewRead: {
            /** Id */
            id: number;
            /**
             * Direction
             * @description about_owner — отзыв о владельце, about_renter — об арендаторе
             */
            direction: string;
            /** Rating */
            rating: number;
            /** Text */
            text: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Author Name
             * @description Имя и первая буква фамилии: «Анна К.»
             */
            author_name: string;
            /** Equipment Name */
            equipment_name: string;
        };
        /**
         * SpecItem
         * @description Характеристика: «Глубина копания» → «5,9 м». Строки, потому что так их пишут люди.
         */
        SpecItem: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** SpecTemplateItem */
        SpecTemplateItem: {
            /** Name */
            name: string;
            /**
             * Example
             * @description Пример значения: «20 т», «6×4»
             */
            example?: string | null;
        };
        /** TelegramLink */
        TelegramLink: {
            /** Url */
            url: string;
        };
        /** TelegramStatus */
        TelegramStatus: {
            /** Enabled */
            enabled: boolean;
            /** Connected */
            connected: boolean;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone?: string | null;
            /**
             * Role
             * @default client
             * @enum {string}
             */
            role: "client" | "owner";
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string | null;
            role: components["schemas"]["UserRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Telegram Connected */
            telegram_connected: boolean;
        };
        /** UserReviews */
        UserReviews: {
            /** Rating */
            rating: number | null;
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ReviewRead"][];
        };
        /** UserReviewsSummary */
        UserReviewsSummary: {
            /** Rating */
            rating: number | null;
            /** Count */
            count: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "client" | "owner" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "service-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    "auth-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-list_categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
        };
    };
    "catalog-list_equipment": {
        parameters: {
            query?: {
                /** @description slug категории */
                category?: string | null;
                /** @description Поиск по названию */
                q?: string | null;
                /** @description Максимальная цена за час */
                price_max?: number | string | null;
                lat?: number | null;
                lon?: number | null;
                radius_km?: number | null;
                available_from?: string | null;
                available_to?: string | null;
                sort?: "new" | "price_asc" | "price_desc" | "distance";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-create_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-get_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-delete_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-update_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-list_my_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-upload_photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_catalog-upload_photos"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "catalog-delete_photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
                photo_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-equipment_busy": {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusyInterval"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-quote_booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-create_booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-my_bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-cancel_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-owner_bookings": {
        parameters: {
            query?: {
                status?: components["schemas"]["BookingStatus"][] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-confirm_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-reject_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-start_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "bookings-complete_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "telegram-telegram_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "telegram-create_link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "telegram-remove_link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "geo-geo_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoStatus"];
                };
            };
        };
    };
    "geo-geo_search": {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoSuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "geo-geo_reverse": {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoSuggestion"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "reviews-review_owner": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "reviews-review_renter": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "reviews-owner_reviews": {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                owner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserReviews"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "reviews-renter_reviews": {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                renter_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserReviews"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "reviews-my_ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRatings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-list_users": {
        parameters: {
            query?: {
                /** @description Имя, email или телефон */
                q?: string | null;
                role?: components["schemas"]["UserRole"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AdminUserRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-delete_user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-list_equipment": {
        parameters: {
            query?: {
                /** @description Название техники */
                q?: string | null;
                status?: components["schemas"]["EquipmentStatus"] | null;
                /** @description slug категории */
                category?: string | null;
                /** @description Только техника этого владельца */
                user_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AdminEquipmentRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-delete_equipment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-list_bookings": {
        parameters: {
            query?: {
                /** @description Техника, клиент или номер брони */
                q?: string | null;
                status?: components["schemas"]["BookingStatus"][] | null;
                /** @description Брони этого аккаунта: как клиента или как владельца */
                user_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BookingRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-delete_booking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-list_reviews": {
        parameters: {
            query?: {
                direction?: components["schemas"]["ReviewDirection"] | null;
                /** @description Например, 2 — только плохие отзывы */
                max_rating?: number | null;
                /** @description Отзывы этого аккаунта: о нём или от него */
                user_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AdminReviewRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-delete_review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-create_category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-update_category": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-delete_category": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
