"""telegram notifications

Revision ID: ac001aedae3f
Revises: 8e058a2b16b8
Create Date: 2026-10-07 15:57:53.077062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac001aedae3f'
down_revision: Union[str, Sequence[str], None] = '8e058a2b16b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('telegram_link_code', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('telegram_link_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(op.f('uq_users_telegram_chat_id'), 'users', ['telegram_chat_id'])
    op.create_unique_constraint(op.f('uq_users_telegram_link_code'), 'users', ['telegram_link_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_telegram_link_code'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_telegram_chat_id'), 'users', type_='unique')
    op.drop_column('users', 'telegram_link_expires_at')
    op.drop_column('users', 'telegram_link_code')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
