"""equipment photos and address

Revision ID: f66f4f46b5a8
Revises: 0d7116effc1b
Create Date: 2026-10-07 14:30:05.132391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66f4f46b5a8'
down_revision: Union[str, Sequence[str], None] = '0d7116effc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CATEGORIES = [
    {"name": "Экскаваторы-погрузчики", "slug": "excavator-loaders"},
    {"name": "Мини-экскаваторы", "slug": "mini-excavators"},
    {"name": "Гусеничные экскаваторы", "slug": "crawler-excavators"},
    {"name": "Фронтальные погрузчики", "slug": "wheel-loaders"},
    {"name": "Автокраны", "slug": "truck-cranes"},
    {"name": "Манипуляторы", "slug": "manipulators"},
    {"name": "Самосвалы", "slug": "dump-trucks"},
    {"name": "Катки", "slug": "rollers"},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_equipment_photos_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_photos')),
    sa.UniqueConstraint('filename', name=op.f('uq_equipment_photos_filename'))
    )
    op.create_index(op.f('ix_equipment_photos_equipment_id'), 'equipment_photos', ['equipment_id'], unique=False)
    op.add_column('equipment', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

    # Добавлено вручную: справочник категорий техники
    categories = sa.table(
        "categories", sa.column("name", sa.String), sa.column("slug", sa.String)
    )
    op.bulk_insert(categories, CATEGORIES)

    # Добавлено вручную: характеристики из объекта {"имя": "значение"} в упорядоченный список
    op.alter_column("equipment", "specs", server_default=sa.text("'[]'::jsonb"))
    op.execute("""
        UPDATE equipment SET specs = COALESCE(
            (SELECT jsonb_agg(jsonb_build_object('name', key, 'value', value))
             FROM jsonb_each_text(specs)),
            '[]'::jsonb)
        WHERE jsonb_typeof(specs) = 'object'
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
        UPDATE equipment SET specs = COALESCE(
            (SELECT jsonb_object_agg(item->>'name', item->>'value')
             FROM jsonb_array_elements(specs) AS item),
            '{}'::jsonb)
        WHERE jsonb_typeof(specs) = 'array'
    """)
    op.alter_column("equipment", "specs", server_default=sa.text("'{}'::jsonb"))
    op.execute(
        sa.text("DELETE FROM categories WHERE slug = ANY(:slugs)").bindparams(
            slugs=[c["slug"] for c in CATEGORIES]
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'address')
    op.drop_index(op.f('ix_equipment_photos_equipment_id'), table_name='equipment_photos')
    op.drop_table('equipment_photos')
    # ### end Alembic commands ###
