"""Избранное, закрытие времени владельцем, восстановление пароля, согласие на обработку данных

Revision ID: 2503a50b55f8
Revises: 9da01d2851eb
Create Date: 2026-10-08 01:53:14.036471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2503a50b55f8'
down_revision: Union[str, Sequence[str], None] = '9da01d2851eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


WHERE_OLD = "status IN ('pending', 'confirmed', 'active')"
WHERE_NEW = "status IN ('pending', 'confirmed', 'active', 'blocked')"


def recreate_overlap_constraint(where: str) -> None:
    op.drop_constraint("bookings_no_overlap", "bookings")
    op.execute(
        "ALTER TABLE bookings ADD CONSTRAINT bookings_no_overlap EXCLUDE USING gist "
        f"(equipment_id WITH =, period WITH &&) WHERE ({where})"
    )


def upgrade() -> None:
    """Upgrade schema."""
    # Новое значение enum нельзя использовать в той же транзакции, где его добавили,
    # поэтому ADD VALUE выполняется отдельной фиксацией
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'blocked'")
    # Закрытое владельцем время участвует в той же проверке пересечений, что и брони
    recreate_overlap_constraint(WHERE_NEW)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_favorites_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'equipment_id', name=op.f('pk_favorites'))
    )
    op.create_index(op.f('ix_favorites_equipment_id'), 'favorites', ['equipment_id'], unique=False)
    op.add_column('users', sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_reset_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(op.f('uq_users_password_reset_hash'), 'users', ['password_reset_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM bookings WHERE status = 'blocked'")
    recreate_overlap_constraint(WHERE_OLD)
    # Значение 'blocked' остаётся в enum: удалить его можно только пересозданием типа, а вреда от него нет
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_password_reset_hash'), 'users', type_='unique')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'password_reset_expires_at')
    op.drop_column('users', 'password_reset_hash')
    op.drop_column('users', 'consent_at')
    op.drop_index(op.f('ix_favorites_equipment_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
