"""initial schema

Revision ID: 0d7116effc1b
Revises: 
Create Date: 2026-10-07 14:01:37.224825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d7116effc1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Добавлено вручную: btree_gist нужен для bookings_no_overlap
    # (GiST-индекс по обычному integer equipment_id вместе с диапазоном period)
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('client', 'owner', 'admin', name='user_role'), server_default='client', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_shift', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_hours', sa.Integer(), server_default='4', nullable=False),
    sa.Column('operator_available', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('operator_price_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('available', 'maintenance', 'inactive', name='equipment_status'), server_default='available', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_equipment_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_equipment_longitude_range')),
    sa.CheckConstraint('min_hours >= 1', name=op.f('ck_equipment_min_hours_positive')),
    sa.CheckConstraint('price_per_hour > 0', name=op.f('ck_equipment_price_per_hour_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_equipment_category_id_categories')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_equipment_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment'))
    )
    op.create_index(op.f('ix_equipment_category_id'), 'equipment', ['category_id'], unique=False)
    op.create_index(op.f('ix_equipment_owner_id'), 'equipment', ['owner_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('period', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('with_operator', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'active', 'completed', 'cancelled', name='booking_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('equipment_id'), '='), (sa.column('period'), '&&'), where=sa.text("status IN ('pending', 'paid', 'active')"), using='gist', name='bookings_no_overlap'),
    sa.CheckConstraint('NOT isempty(period)', name=op.f('ck_bookings_period_not_empty')),
    sa.CheckConstraint('total_price >= 0', name=op.f('ck_bookings_total_price_non_negative')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_bookings_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_equipment_id'), 'bookings', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_equipment_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_equipment_owner_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_category_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###

    # Добавлено вручную: Alembic не удаляет enum-типы вместе с таблицами
    op.execute("DROP TYPE IF EXISTS booking_status")
    op.execute("DROP TYPE IF EXISTS equipment_status")
    op.execute("DROP TYPE IF EXISTS user_role")
